name: Dummy File
on: 
    push: 
        branches: 
            - master
env:
    SCHOOL: ${{secrets.SCHOOL}}
jobs:
    info:
        runs-on: ubuntu-latest
        env:
            NAME: ${{secrets.NAME}}
        steps:

            - name: Get Code
              uses: actions/checkout@v4
            - name: Run Code
              run:  node index.js
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print School
              run: echo "MY school is $SCHOOL"
            - name: Print Name from info
              run: echo "${{env.NAME}}"