name: Dummy File
on: 
    push: 
        branches: 
            - master
env:
    SCHOOL: ${{secrets.SCHOOL}}
jobs:
    info:
        runs-on: ubuntu-latest
        env:
            NAME: ${{secrets.NAME}}
        steps:

            - name: Get Code
              uses: actions/checkout@v4
            - name: Get Bun
              uses: oven-sh/setup-bun@v1
            - name: Install Dependencies
              run: bun install
            - name:  Run Code
              run: bun app.js
              timeout-minutes: 1
                
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print School
              run: echo "MY school is $SCHOOL"
            - name: Print Name from info
              run: echo "${{env.NAME}}"
    build:
      runs-on: ubuntu-latest
      environment: build
      env:
        NAME: ${{secrets.NAME}}
        RELATION: ${{secrets.RELATION}}
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Get Bun
          uses: oven-sh/setup-bun@v1
        - name: Install Dependencies
          run: bun install
        - name:  Run Code
          run: bun index.js
          
          